singleNode: false
replicas: 1
config:
  opensearch.yml: |-
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0
extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: Fr3und3nEck5685!

service:
  type: LoadBalancer
