apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-models
  namespace: vllm
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: vllm-nfs-client
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: hf-token-secret
  namespace: vllm
type: Opaque
stringData:
  token: "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"
