apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc
  namespace: longhorn-system 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn # Specifies Longhorn as the storage provider
  volumeName: longhorn-pv
