apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-open-webui-pvc
  namespace: open-webui
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: open-webui-nfs-client
