apiVersion: v1
kind: Pod
metadata:
  name: devicequery
spec:
  restartPolicy: OnFailure
  nodeSelector:
   node-type: jetson
  containers:
  - name: devicequery
    image: "jitteam/devicequery:latest"
    command: ["./deviceQuery"]
