apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
  namespace: docker-registry
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: docker-nfs-client
