apiVersion: v1
kind: Secret
namespace: docker-registry
metadata:
  name: docker-registry-tls
type: kubernetes.io/tls
data:
  tls.crt: <paste_your_base64_encoded_cert_here>
  tls.key: <paste_your_base64_encoded_key_here>
