apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster
  namespace: rabbitmq
spec:
  replicas: 1
  persistence:
    storageClassName: local-path
    storage: 20Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "rabbitmq" 
            operator: "In"
            values:
            - "true" 
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  rabbitmq:
     additionalPlugins:
     - rabbitmq_management
     - rabbitmq_shovel
     - rabbitmq_prometheus
     additionalConfig: |
        log.console.level = info
        channel_max = 700
        default_user= admin 
        default_pass = admin
        default_user_tags.administrator = true

        # https://www.rabbitmq.com/configure.html
        vm_memory_high_watermark.absolute = 2GB
        vm_memory_high_watermark_paging_ratio = 0.99

        # Statistics collection interval in milliseconds (default=5000)
        collect_statistics_interval = 5000

        # supported values: basic, detailed, none
        # default=basic
        management.rates_mode = basic

        # defaults: 5, 60, 1800
        management.sample_retention_policies.global.minute = 10
        management.sample_retention_policies.global.hour = 300
        management.sample_retention_policies.global.day = 1800

        # defaults: 5, 60
        management.sample_retention_policies.basic.minute = 10
        management.sample_retention_policies.basic.hour = 300

        # management metrics can be disabled altogether
        management_agent.disable_metrics_collector = false

        # default:  5
        management.sample_retention_policies.detailed.10 = 60
  service:
    type: LoadBalancer


