apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-pvc
  namespace: llama-cpp
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
