apiVersion: v1
kind: Secret
metadata:
  name: terraform-mcp-secret
  namespace: terraform
type: Opaque
data:
  tfe-token: "MHhXOVZaSkFkV3Zjd0EudGF0bGF2MS5BaTN4cHJmNHRUMlFrdDBCeEtFSm1rWG0waVNBSUgxRlVzR3piY01CdXhBd3RiOUxzVFJvMVhUZWcxQ1ZvZ3o1NFBF"
  organization: "U2FtbGFuZC1MYWI="