apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-model-pvc
  namespace: comfyui
spec:
  storageClassName: comfyui-nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
