apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-longhorn-pvc
  namespace: ollama
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi

