---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
  namespace: minio
spec:
  storageClassName: minio-nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
