# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
data:
  rootUser: YWRtaW4=
  rootPassword: cGFzc3dvcmQ=
