# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
data:
  MINIO_ROOT_USER: YWRtaW4=
  MINIO_ROOT_PASSWORD: YWRtaW4=
