mode: standalone

existingSecret: minio

replicas: 1

image:
  repository: quay.io/minio/minio
  tag: RELEASE.2025-09-07T16-13-09Z-cpuv1
  pullPolicy: IfNotPresent

mcImage:
  repository: quay.io/minio/mc
  tag: RELEASE.2025-08-13T08-35-41Z-cpuv1
  pullPolicy: IfNotPresent


persistence:
  enabled: true
  existingClaim: s3-pvc
#  storageClass: "minio-nfs-client"
#  accessMode: ReadWriteMany
  size: 100Gi

resources:
  requests:
    memory: 4Gi

metrics:
  serviceMonitor:
    enabled: true
    includeNode: true


consoleService:
  type: LoadBalancer
  port: 9001

postJob: {}
 
nodeSelector: 
  kubernetes.io/hostname: turing-four

