apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc-lp
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi

