apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc-lh
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi

