apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurite-pvc
  namespace: azurite
spec:
  accessModes:
  - ReadWriteOnce 
  storageClassName: local-path  # Use a storage class appropriate for your cluster
  resources:
    requests:
      storage: 50Gi # Request the desired storage size

