apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  type: LoadBalancer
  selector:
    app: redis-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-server
  namespace: redis
spec:
  serviceName: "redis"
  replicas: 2
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      nodeSelector:
        redis: "true"
      containers:
        - name: redis-server
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
             claimName: redis-pvc

